name: Example Workflow
on:
  pull_request:

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.29.2

      - name: Test
        run: |
            flutter test --coverage --coverage-path coverage/lcov.info
      
      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1

      - uses: snkrdunk/octocov-action@main
